name: Deploy app
on:
  push:
    braches: ['develop']
    workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: '1.0.7'
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKERHUB_USERNAME
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image
        run: docker build -t $DOCKERHUB_USERNAME/vue3:$MY_VARIABLE .

      - name: Push to docker hub
        run: docker push
