name: Deploy app
on:
  push:
    braches: ['develop']
    workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: '1.0.7'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vue3:1.0.7 .

      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vue3:1.0.7
